version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: database_container_tj
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgressdb 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: api_container_tj
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend_container_tj
    build:
      context: ./front-angular
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./:/front-angular
    environment:
      - STYLE=css
    depends_on:
      - api 

volumes:
  postgres_data: